CREATE TABLE Armazem_Colheita (
  id                     number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Instalação_Agricola_id number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Armazem_Factor_De_Produção (
  id                     number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Instalação_Agricola_id number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Armazem_Ração_Animal (
  id                     number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Instalação_Agricola_id number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Armazem_Ração_Animal_Ração_Animal (
  Armazem_Ração_Animal_id number(10) NOT NULL, 
  Ração_Animal_id         number(10) NOT NULL, 
  PRIMARY KEY (Armazem_Ração_Animal_id, 
  Ração_Animal_id));
CREATE TABLE Cabaz (
  id                      number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Preço                   float(10) NOT NULL, 
  Data_De_Registo         date NOT NULL, 
  Rede_De_Distribuição_id number(10) NOT NULL, 
  Instalação_Agricola_id  number(10) NOT NULL, 
  Encomenda_id            number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Cabaz_Produto (
  Cabaz_id   number(10) NOT NULL, 
  Produto_id number(10) NOT NULL, 
  PRIMARY KEY (Cabaz_id, 
  Produto_id));
CREATE TABLE Caderno_De_Campo (
  id                 number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Gestor_Agricola_id number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Cliente (
  id                        number(10) NOT NULL, 
  Nome                      varchar2(50) NOT NULL, 
  Numero_Fiscal             number(10) NOT NULL UNIQUE, 
  Email                     varchar2(50) NOT NULL UNIQUE, 
  Plafond                   float(10) NOT NULL, 
  Morada_Correspondencia_id number(10) NOT NULL, 
  Morada_Entrega_id         number(10) NOT NULL,
  Quantidade_Encomendas_Ultimo_Ano number(10) NOT NULL,
  Acumulado_Encomendas_Ultimo_Ano  float(10) NOT NULL,
  PRIMARY KEY (id, 
  Morada_Correspondencia_id, 
  Morada_Entrega_id));
CREATE TABLE Colheita (
  id                  number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Data                date NOT NULL, 
  Quantidade          number(10) NOT NULL, 
  Armazem_Colheita_id number(10) NOT NULL, 
  Produto_id          number(10) NOT NULL, 
  Parcela_Agricola_id number(10) NOT NULL, 
  Caderno_De_Campo_id number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Condutor (
  id    number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Nome  varchar2(50) NOT NULL, 
  Email varchar2(50) NOT NULL UNIQUE, 
  PRIMARY KEY (id));
CREATE TABLE Controlador (
  id                 number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Sistema_De_Rega_id number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Cultura (
  id             number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Nome_Comercial varchar2(50) NOT NULL, 
  Tipo           varchar2(50) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Electrovalvulas (
  id             number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Controlador_id number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Elemento_Nutritivo_Organico (
  id         number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Designação varchar2(50) NOT NULL, 
  Quantidade varchar2(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Encomenda (
  id                                number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Rede_De_Distribuição_id           number(10) NOT NULL, 
  Estado_Encomenda                  varchar2(50) NOT NULL, 
  Data_Registo                      date NOT NULL, 
  Data_Pagamento                    date, 
  Data_Entrega                      date NOT NULL, 
  Cliente_id                        number(10) NOT NULL, 
  Cliente_Morada_Correspondencia_id number(10) NOT NULL, 
  Cliente_Morada_Entrega_id         number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Estabulo_Animal (
  id                     number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Instalação_Agricola_id number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Estação_Meteorologica (
  id                     number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Instalação_Agricola_id number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Factor_De_Produção (
  id               number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Nome_Comercial   varchar2(50) NOT NULL, 
  Tipo             varchar2(50) NOT NULL, 
  Formulação       varchar2(20) NOT NULL,
  Fornecedor       varchar2(255) NOT NULL,
  Ficha_Tecnica_id number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Factor_De_Produção_Armazem_Factor_De_Produção (
  Factor_De_Produção_id         number(10) NOT NULL, 
  Armazem_Factor_De_Produção_id number(10) NOT NULL, 
  PRIMARY KEY (Factor_De_Produção_id, 
  Armazem_Factor_De_Produção_id));
CREATE TABLE Fertilização (
  id                    number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Caderno_De_Campo_id   number(10) NOT NULL, 
  Factor_De_Produção_id number(10) NOT NULL, 
  Parcela_Agricola_id   number(10) NOT NULL, 
  Metodo_Aplicação      varchar2(100), 
  Data                  date, 
  Quantidade            number(10), 
  PRIMARY KEY (id));
CREATE TABLE Ficha_Tecnica (
  id number(10) GENERATED BY DEFAULT AS IDENTITY, 
  PRIMARY KEY (id));
CREATE TABLE Ficha_Tecnica_Elemento_Nutritivo_Organico (
  Ficha_Tecnica_id               number(10) NOT NULL, 
  Elemento_Nutritivo_Organico_id number(10) NOT NULL, 
  PRIMARY KEY (Ficha_Tecnica_id, 
  Elemento_Nutritivo_Organico_id));
CREATE TABLE Ficha_Tecnica_Substancia_Organica (
  Ficha_Tecnica_id       number(10) NOT NULL, 
  Substancia_Organica_id number(10) NOT NULL, 
  PRIMARY KEY (Ficha_Tecnica_id, 
  Substancia_Organica_id));
CREATE TABLE Filtro (
  id    number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Marca varchar2(20) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Garagem_Maquinas_Alfaias (
  id                     number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Instalação_Agricola_id number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Gestor_Agricola (
  id    number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Nome  varchar2(50) NOT NULL, 
  Email varchar2(50) NOT NULL UNIQUE, 
  PRIMARY KEY (id));
CREATE TABLE Gestor_De_Distribuição (
  id    number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Nome  varchar2(50) NOT NULL, 
  Email varchar2(50) NOT NULL UNIQUE, 
  PRIMARY KEY (id));
CREATE TABLE Incidente (
  id                               number(10) NOT NULL, 
  Cliente_id                       number(10) NOT NULL, 
  Valor                            number(10) NOT NULL, 
  Data_Ocorrencia                  date NOT NULL, 
  Data_Sanado                      date NOT NULL, 
  ClienteMorada_Correspondencia_id number(10) NOT NULL, 
  ClienteMorada_Entrega_id         number(10) NOT NULL, 
  PRIMARY KEY (id, 
  ClienteMorada_Correspondencia_id, 
  ClienteMorada_Entrega_id));
CREATE TABLE Instalação_Agricola (
  id number(10) GENERATED BY DEFAULT AS IDENTITY, 
  PRIMARY KEY (id));
CREATE TABLE Instalação_Agricola_Rede_De_Distribuição (
  Instalação_Agricola_id  number(10) NOT NULL, 
  Rede_De_Distribuição_id number(10) NOT NULL, 
  PRIMARY KEY (Instalação_Agricola_id, 
  Rede_De_Distribuição_id));
CREATE TABLE Morada (
  id            number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Codigo_Postal varchar2(8) NOT NULL, 
  Localidade    varchar2(100) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Parcela_Agricola (
  id                     number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Designação             varchar2(50) NOT NULL, 
  Area                   varchar2(100) NOT NULL, 
  Cultura_id             number(10) NOT NULL, 
  Instalação_Agricola_id number(10) NOT NULL, 
  Sistema_De_Rega_id     number(10) NOT NULL, 
  Gestor_Agricola_id     number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Plano_De_Rega (
  id                  number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Sistema_De_Rega_id  number(10) NOT NULL, 
  Caderno_De_Campo_id number(10) NOT NULL, 
  Ordem_Rega          number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Produto (
  id    number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Nome  varchar2(255) NOT NULL, 
  Preço float(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Ração_Animal (
  id number(10) GENERATED BY DEFAULT AS IDENTITY, 
  PRIMARY KEY (id));
CREATE TABLE Rede_De_Distribuição (
  id                        number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Tipo_De_Venda             varchar2(100) NOT NULL, 
  Gestor_De_Distribuição_id number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Rede_De_Distribuição_Condutor (
  Rede_De_Distribuição_id number(10) NOT NULL, 
  Condutor_id             number(10) NOT NULL, 
  PRIMARY KEY (Rede_De_Distribuição_id, 
  Condutor_id));
CREATE TABLE Rega (
  id                  number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Data                date NOT NULL, 
  Tempo               number(10) NOT NULL, 
  Periodicidade       number(10) NOT NULL, 
  Plano_De_Rega_id    number(10) NOT NULL, 
  Parcela_Agricola_id number(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Sensor (
  id                       number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Estação_Meteorologica_id number(10) NOT NULL, 
  Tipo                     varchar2(25) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Sistema_De_Rega (
  id                   number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Dimensão             number(10) NOT NULL, 
  Tipo_De_Rega         varchar2(20) NOT NULL, 
  Tipo_De_Distribuição varchar2(30) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Sistema_De_Rega_Filtro (
  Sistema_De_Rega_id number(10) NOT NULL, 
  Filtro_id          number(10) NOT NULL, 
  PRIMARY KEY (Sistema_De_Rega_id, 
  Filtro_id));
CREATE TABLE Substancia_Organica (
  id         number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Designação varchar2(50) NOT NULL, 
  Quantidade varchar2(10) NOT NULL, 
  PRIMARY KEY (id));
CREATE TABLE Valor_Sensor (
  id                  number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Valor_Medido        number(10) NOT NULL, 
  Data                timestamp(0) NOT NULL, 
  Sensor_id           number(10) NOT NULL, 
  Caderno_De_Campo_id number(10) NOT NULL, 
  PRIMARY KEY (id));
