ALTER TABLE Armazem_Ração_Animal_Ração_Animal ADD CONSTRAINT FK_Armazem_Ração_Animal_Ração_Animal_Armazem_Ração_Animal FOREIGN KEY (Armazem_Ração_Animal_id) REFERENCES Armazem_Ração_Animal (id);
ALTER TABLE Armazem_Ração_Animal_Ração_Animal ADD CONSTRAINT FK_Armazem_Ração_Animal_Ração_Animal_Ração_Animal FOREIGN KEY (Ração_Animal_id) REFERENCES Ração_Animal (id);
ALTER TABLE Ficha_Tecnica_Substancia_Organica ADD CONSTRAINT FK_Ficha_Tecnica_Substancia_Organica_Ficha_Tecnica FOREIGN KEY (Ficha_Tecnica_id) REFERENCES Ficha_Tecnica (id);
ALTER TABLE Ficha_Tecnica_Substancia_Organica ADD CONSTRAINT FK_Ficha_Tecnica_Substancia_Organica_Substancia_Organica FOREIGN KEY (Substancia_Organica_id) REFERENCES Substancia_Organica (id);
ALTER TABLE Ficha_Tecnica_Elemento_Nutritivo_Organico ADD CONSTRAINT FK_Ficha_Tecnica_Elemento_Nutritivo_Organico_Ficha_Tecnica FOREIGN KEY (Ficha_Tecnica_id) REFERENCES Ficha_Tecnica (id);
ALTER TABLE Ficha_Tecnica_Elemento_Nutritivo_Organico ADD CONSTRAINT FK_Ficha_Tecnica_Elemento_Nutritivo_Organico_ FOREIGN KEY (Elemento_Nutritivo_Organico_id) REFERENCES Elemento_Nutritivo_Organico (id);
ALTER TABLE Factor_De_Produção_Armazem_Factor_De_Produção ADD CONSTRAINT FK_Factor_De_Produção_Armazem_Factor_De_Produção_Elemento_Nutritivo_Organico FOREIGN KEY (Factor_De_Produção_id) REFERENCES Factor_De_Produção (id);
ALTER TABLE Factor_De_Produção_Armazem_Factor_De_Produção ADD CONSTRAINT FK_Factor_De_Produção_Armazem_Factor_De_Produção_Armazem_Factor_De_Produção FOREIGN KEY (Armazem_Factor_De_Produção_id) REFERENCES Armazem_Factor_De_Produção (id);
ALTER TABLE Parcela_Agricola ADD CONSTRAINT FK_Parcela_Agricola_Cultura FOREIGN KEY (Cultura_id) REFERENCES Cultura (id);
ALTER TABLE Parcela_Agricola ADD CONSTRAINT FK_Parcela_Agricola_Instalação_Agricola FOREIGN KEY (Instalação_Agricola_id) REFERENCES Instalação_Agricola (id);
ALTER TABLE Armazem_Factor_De_Produção ADD CONSTRAINT FK_Armazem_Factor_De_Produção_Instalação_Agricola FOREIGN KEY (Instalação_Agricola_id) REFERENCES Instalação_Agricola (id);
ALTER TABLE Estabulo_Animal ADD CONSTRAINT FK_Estabulo_Animal_Instalação_Agricola FOREIGN KEY (Instalação_Agricola_id) REFERENCES Instalação_Agricola (id);
ALTER TABLE Garagem_Maquinas_Alfaias ADD CONSTRAINT FK_Garagem_Maquinas_Alfaias_Instalação_Agricola FOREIGN KEY (Instalação_Agricola_id) REFERENCES Instalação_Agricola (id);
ALTER TABLE Armazem_Ração_Animal ADD CONSTRAINT FK_Armazem_Ração_Animal_Instalação_Agricola FOREIGN KEY (Instalação_Agricola_id) REFERENCES Instalação_Agricola (id);
ALTER TABLE Armazem_Colheita ADD CONSTRAINT FK_Armazem_Colheita_Instalação_Agricola FOREIGN KEY (Instalação_Agricola_id) REFERENCES Instalação_Agricola (id);
ALTER TABLE Factor_De_Produção ADD CONSTRAINT FK_Factor_De_Produção_Ficha_Tecnica FOREIGN KEY (Ficha_Tecnica_id) REFERENCES Ficha_Tecnica (id);
ALTER TABLE Estação_Meteorologica ADD CONSTRAINT FK_Estação_Meteorologica_Instalação_Agricola FOREIGN KEY (Instalação_Agricola_id) REFERENCES Instalação_Agricola (id);
ALTER TABLE Sensor ADD CONSTRAINT FK_Sensor_Estação_Meteorologica FOREIGN KEY (Estação_Meteorologica_id) REFERENCES Estação_Meteorologica (id);
ALTER TABLE Sistema_De_Rega_Filtro ADD CONSTRAINT FK_Sistema_De_Rega_Filtro_Sistema_De_Rega FOREIGN KEY (Sistema_De_Rega_id) REFERENCES Sistema_De_Rega (id);
ALTER TABLE Sistema_De_Rega_Filtro ADD CONSTRAINT FK_Sistema_De_Rega_Filtro_Filtro FOREIGN KEY (Filtro_id) REFERENCES Filtro (id);
ALTER TABLE Controlador ADD CONSTRAINT FK_Controlador_Sistema_De_Rega FOREIGN KEY (Sistema_De_Rega_id) REFERENCES Sistema_De_Rega (id);
ALTER TABLE Electrovalvulas ADD CONSTRAINT FK_Electrovalvulas_Controlador FOREIGN KEY (Controlador_id) REFERENCES Controlador (id);
ALTER TABLE Parcela_Agricola ADD CONSTRAINT FK_Parcela_Agricola_Sistema_De_Rega FOREIGN KEY (Sistema_De_Rega_id) REFERENCES Sistema_De_Rega (id);
ALTER TABLE Plano_De_Rega ADD CONSTRAINT FK_Plano_De_Rega_Sistema_De_Rega FOREIGN KEY (Sistema_De_Rega_id) REFERENCES Sistema_De_Rega (id);
ALTER TABLE Cabaz_Produto ADD CONSTRAINT FK_Cabaz_Produto_Cabaz FOREIGN KEY (Cabaz_id) REFERENCES Cabaz (id);
ALTER TABLE Cabaz_Produto ADD CONSTRAINT FK_Cabaz_Produto_Produto FOREIGN KEY (Produto_id) REFERENCES Produto (id);
ALTER TABLE Cabaz ADD CONSTRAINT FK_Cabaz_Rede_De_Distribuição FOREIGN KEY (Rede_De_Distribuição_id) REFERENCES Rede_De_Distribuição (id);
ALTER TABLE Cabaz ADD CONSTRAINT FK_Cabaz_Instalação_Agricola FOREIGN KEY (Instalação_Agricola_id) REFERENCES Instalação_Agricola (id);
ALTER TABLE Encomenda ADD CONSTRAINT FK_Encomenda_Rede_De_Distribuição FOREIGN KEY (Rede_De_Distribuição_id) REFERENCES Rede_De_Distribuição (id);
ALTER TABLE Instalação_Agricola_Rede_De_Distribuição ADD CONSTRAINT FK_Instalação_Agricola_Rede_De_Distribuição_Instalação_Agricola FOREIGN KEY (Instalação_Agricola_id) REFERENCES Instalação_Agricola (id);
ALTER TABLE Instalação_Agricola_Rede_De_Distribuição ADD CONSTRAINT FK_Instalação_Agricola_Rede_De_Distribuição_Rede_De_Distribuição FOREIGN KEY (Rede_De_Distribuição_id) REFERENCES Rede_De_Distribuição (id);
ALTER TABLE Caderno_De_Campo ADD CONSTRAINT FK_Caderno_De_Campo_Gestor_Agricola FOREIGN KEY (Gestor_Agricola_id) REFERENCES Gestor_Agricola (id);
ALTER TABLE Parcela_Agricola ADD CONSTRAINT FK_Parcela_Agricola_Gestor_Agricola FOREIGN KEY (Gestor_Agricola_id) REFERENCES Gestor_Agricola (id);
ALTER TABLE Valor_Sensor ADD CONSTRAINT FK_Valor_Sensor_Sensor FOREIGN KEY (Sensor_id) REFERENCES Sensor (id);
ALTER TABLE Valor_Sensor ADD CONSTRAINT FK_Valor_Sensor_Caderno_De_Campo FOREIGN KEY (Caderno_De_Campo_id) REFERENCES Caderno_De_Campo (id);
ALTER TABLE Colheita ADD CONSTRAINT FK_Colheita_Armazem_Colheita FOREIGN KEY (Armazem_Colheita_id) REFERENCES Armazem_Colheita (id);
ALTER TABLE Colheita ADD CONSTRAINT FK_Colheita_Produto FOREIGN KEY (Produto_id) REFERENCES Produto (id);
ALTER TABLE Colheita ADD CONSTRAINT FK_Colheita_Parcela_Agricola FOREIGN KEY (Parcela_Agricola_id) REFERENCES Parcela_Agricola (id);
ALTER TABLE Colheita ADD CONSTRAINT FK_Colheita_Caderno_De_Campo FOREIGN KEY (Caderno_De_Campo_id) REFERENCES Caderno_De_Campo (id);
ALTER TABLE Fertilização ADD CONSTRAINT FK_Fertilização_Caderno_De_Campo FOREIGN KEY (Caderno_De_Campo_id) REFERENCES Caderno_De_Campo (id);
ALTER TABLE Fertilização ADD CONSTRAINT FK_Fertilização_Factor_De_Produção FOREIGN KEY (Factor_De_Produção_id) REFERENCES Factor_De_Produção (id);
ALTER TABLE Fertilização ADD CONSTRAINT FK_Fertilização_Parcela_Agricola FOREIGN KEY (Parcela_Agricola_id) REFERENCES Parcela_Agricola (id);
ALTER TABLE Plano_De_Rega ADD CONSTRAINT FK_Plano_De_Rega_Caderno_De_Campo FOREIGN KEY (Caderno_De_Campo_id) REFERENCES Caderno_De_Campo (id);
ALTER TABLE Rega ADD CONSTRAINT FK_Rega_Plano_De_Rega FOREIGN KEY (Plano_De_Rega_id) REFERENCES Plano_De_Rega (id);
ALTER TABLE Rega ADD CONSTRAINT FK_Rega_Parcela_Agricola FOREIGN KEY (Parcela_Agricola_id) REFERENCES Parcela_Agricola (id);
ALTER TABLE Rede_De_Distribuição_Condutor ADD CONSTRAINT FK_Rede_De_Distribuição_Condutor_Rede_De_Distribuição FOREIGN KEY (Rede_De_Distribuição_id) REFERENCES Rede_De_Distribuição (id);
ALTER TABLE Rede_De_Distribuição_Condutor ADD CONSTRAINT FK_Rede_De_Distribuição_Condutor_Condutor FOREIGN KEY (Condutor_id) REFERENCES Condutor (id);
ALTER TABLE Rede_De_Distribuição ADD CONSTRAINT FK_Rede_De_Distribuição_Gestor_De_Distribuição FOREIGN KEY (Gestor_De_Distribuição_id) REFERENCES Gestor_De_Distribuição (id);
ALTER TABLE Incidente ADD CONSTRAINT FK_Incidente_Cliente FOREIGN KEY (Cliente_id, ClienteMorada_Correspondencia_id, ClienteMorada_Entrega_id) REFERENCES Cliente (id, Morada_Correspondencia_id, Morada_Entrega_id);
ALTER TABLE Cabaz ADD CONSTRAINT FK_Cabaz_Encomenda FOREIGN KEY (Encomenda_id) REFERENCES Encomenda (id);
ALTER TABLE Cliente ADD CONSTRAINT FK_Cliente_Morada_Correspondencia FOREIGN KEY (Morada_Correspondencia_id) REFERENCES Morada (id);
ALTER TABLE Cliente ADD CONSTRAINT FK_Cliente_Morada_Entrega FOREIGN KEY (Morada_Entrega_id) REFERENCES Morada (id);
ALTER TABLE Encomenda ADD CONSTRAINT FK_Encomenda_Cliente FOREIGN KEY (Cliente_id, Cliente_Morada_Correspondencia_id, Cliente_Morada_Entrega_id) REFERENCES Cliente (id, Morada_Correspondencia_id, Morada_Entrega_id);

ALTER TABLE Cliente ADD CONSTRAINT CK_Cliente_Numero_Fiscal CHECK (Numero_Fiscal > 99999999 AND Numero_Fiscal < 1000000000);
ALTER TABLE Cliente ADD CONSTRAINT CK_Cliente_Email CHECK (Email like '%@%.%');
ALTER TABLE Condutor ADD CONSTRAINT CK_Condutor_Email CHECK (Email like '%@%.%');
ALTER TABLE Gestor_Agricola ADD CONSTRAINT CK_Gestor_Agricola_Email CHECK (Email like '%@%.%');
ALTER TABLE Gestor_De_Distribuição ADD CONSTRAINT CK_Gestor_De_Distribuição_Email CHECK (Email like '%@%.%');
ALTER TABLE Morada ADD CONSTRAINT CK_Morada_Codigo_Postal CHECK (Codigo_Postal like '____-___');
ALTER TABLE Rede_De_Distribuição ADD CONSTRAINT CK_Rede_De_Distribuição_Tipo_De_Venda CHECK (Tipo_De_Venda LIKE 'Mercado Local' OR Tipo_De_Venda LIKE 'AMAP' OR Tipo_De_Venda LIKE 'Venda Direta' OR Tipo_De_Venda LIKE 'Grupo de Consumo');
ALTER TABLE Factor_De_Produção ADD CONSTRAINT CK_Factor_De_Produção_Formulação CHECK (Formulação LIKE 'líquido' OR Formulação LIKE 'granulado' OR Formulação LIKE 'pó');
ALTER TABLE Factor_De_Produção ADD CONSTRAINT CK_Factor_De_Produção_Tipo CHECK (Tipo LIKE 'fertilizantes' OR Tipo LIKE 'adubos' OR Tipo LIKE 'correctivos' OR Tipo LIKE 'produtos fitofármacos');
ALTER TABLE Encomenda ADD CONSTRAINT CK_Encomenda_Estado_Encomenda CHECK (Estado_Encomenda LIKE 'entregue' OR Estado_Encomenda LIKE 'paga' OR Estado_Encomenda LIKE 'registada');
ALTER TABLE Sensor ADD CONSTRAINT CK_Sensor_Tipo CHECK (Tipo LIKE 'Temperatura' OR Tipo LIKE 'Velocidade Vento' OR Tipo LIKE 'Direção Vento' OR Tipo LIKE 'Humidade Atmosférica' OR Tipo LIKE 'Humidade Solo' OR Tipo LIKE 'Pluviosidade');
ALTER TABLE Fertilização ADD CONSTRAINT CK_Fertilização_Metodo_Aplicação CHECK (Metodo_Aplicação LIKE 'Via Foliar' OR Metodo_Aplicação LIKE 'Fertirega' OR Metodo_Aplicação LIKE 'Aplicação Direta' );
ALTER TABLE Sistema_De_Rega ADD CONSTRAINT CK_Sistema_De_Rega_Tipo_De_Rega CHECK (Tipo_De_Rega LIKE 'Bombeada' OR Tipo_De_Rega LIKE 'Gravidade');
ALTER TABLE Sistema_De_Rega ADD CONSTRAINT CK_Sistema_De_Rega_Tipo_De_Distribuição CHECK (Tipo_De_Distribuição LIKE 'Aspersão' OR Tipo_De_Distribuição LIKE 'Gotejamento' OR Tipo_De_Distribuição LIKE 'Pulverização');
ALTER TABLE Cultura ADD CONSTRAINT CK_Cultura_Tipo CHECK (Tipo LIKE 'Permanente' OR Tipo LIKE 'Temporário');